services:
  web:
    build: .
    volumes:
      - .:/app
      - ldp_data:/app/data
    ports:
      - "127.0.0.1:8001:8001"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],ldp.clouditechsolution.com,*
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/data/db.sqlite3}

volumes:
  ldp_data:
