# Generated by Django 4.2.30 on 2026-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('SCHOLAR', 'Scholar'), ('LEADERSHIP_AWARDEE', 'Leadership Awardee'), ('COLLEGE', 'College'), ('PROFESSIONAL', 'Professional'), ('PRINCIPAL', 'Principal')], default='STUDENT', max_length=50),
        ),
    ]
