# Generated by Django 4.2.30 on 2026-04-25 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0002_alter_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PRINCIPAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_schools', to=settings.AUTH_USER_MODEL),
        ),
    ]
