# Generated by Django 4.2.30 on 2026-04-25 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ldp_core.school'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
