# Generated by Django 4.2.30 on 2026-04-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0006_person_address_person_bio_person_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_pending_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='pending_changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
