# Generated by Django 4.2.30 on 2026-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0007_person_is_pending_approval_person_pending_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='course_program',
            field=models.CharField(blank=True, max_length=255, verbose_name='Course / Program'),
        ),
        migrations.AddField(
            model_name='person',
            name='scholarship_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Scholarship Type / Award'),
        ),
        migrations.AddField(
            model_name='person',
            name='section',
            field=models.CharField(blank=True, max_length=50, verbose_name='Section / Batch'),
        ),
        migrations.AddField(
            model_name='person',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student / Scholar ID'),
        ),
        migrations.AddField(
            model_name='person',
            name='year_ended',
            field=models.CharField(blank=True, max_length=10, verbose_name='Year Ended / Graduated'),
        ),
        migrations.AddField(
            model_name='person',
            name='year_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Year Level / Grade'),
        ),
        migrations.AddField(
            model_name='person',
            name='year_started',
            field=models.CharField(blank=True, max_length=10, verbose_name='Year Started'),
        ),
    ]
