# Generated by Django 4.2.30 on 2026-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0008_person_course_program_person_scholarship_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='school',
            name='division',
            field=models.CharField(blank=True, max_length=100, verbose_name='Division / Department'),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='School Email'),
        ),
        migrations.AddField(
            model_name='school',
            name='founded_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='Year Founded'),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='School ID / EMiS No.'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, choices=[('ELEMENTARY', 'Elementary School'), ('SECONDARY', 'Secondary / Junior High School'), ('SENIOR_HIGH', 'Senior High School'), ('INTEGRATED', 'Integrated School (K–12)'), ('COLLEGE', 'College / University'), ('TECH_VOC', 'Technical-Vocational Institute'), ('SPECIAL', 'Special Education School'), ('OTHER', 'Other')], max_length=50, verbose_name='School Type'),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Category / Classification'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(default='Philippines', max_length=255, verbose_name='City / Municipality'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, verbose_name='School Name'),
        ),
    ]
