# Generated by Django 4.2.30 on 2026-04-25 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0009_school_address_school_district_school_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPrincipalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_name', models.CharField(blank=True, max_length=255, verbose_name='Principal Name')),
                ('assigned_at', models.DateField(verbose_name='Date Assigned')),
                ('removed_at', models.DateField(blank=True, null=True, verbose_name='Date Removed')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_history', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_history', to='ldp_core.school')),
            ],
            options={
                'verbose_name': 'Principal Assignment History',
                'verbose_name_plural': 'Principal Assignment Histories',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
