# Generated by Django 4.2.30 on 2026-04-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0010_schoolprincipalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='activities/banners/', verbose_name='Activity Banner'),
        ),
        migrations.AddField(
            model_name='school',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='schools/banners/', verbose_name='School Banner'),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name='School Logo'),
        ),
    ]
