# Generated by Django 4.2.30 on 2026-04-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0011_activity_banner_school_banner_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('SCHOLAR', 'Scholar'), ('COLLEGE', 'College'), ('PROFESSIONAL', 'Professional'), ('PRINCIPAL', 'Principal')], default='STUDENT', max_length=50),
        ),
        migrations.CreateModel(
            name='LeadershipAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(max_length=255, verbose_name='Award Title')),
                ('award_level', models.CharField(choices=[('SCHOOL', 'School Level'), ('DISTRICT', 'District Level'), ('DIVISION', 'Division Level'), ('REGIONAL', 'Regional Level'), ('NATIONAL', 'National Level')], default='SCHOOL', max_length=50, verbose_name='Award Level')),
                ('year_awarded', models.CharField(max_length=10, verbose_name='Year Awarded')),
                ('awarding_body', models.CharField(blank=True, max_length=255, verbose_name='Awarding Body / Organization')),
                ('description', models.TextField(blank=True, verbose_name='Description / Notes')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='awards/certificates/', verbose_name='Certificate / Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_awards', to='ldp_core.person')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='ldp_core.school', verbose_name='School')),
            ],
            options={
                'ordering': ['-year_awarded', 'award_title'],
            },
        ),
    ]
