# Generated by Django 4.2.30 on 2026-04-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0012_alter_person_type_leadershipaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/banners/', verbose_name='Profile Banner'),
        ),
    ]
