# Generated by Django 4.2.30 on 2026-04-26 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0013_person_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(verbose_name='Transfer Date')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('reason', models.CharField(choices=[('PROMOTION', 'Promotion / Reassignment'), ('RELOCATION', 'Family Relocation'), ('COMPLETION', 'Course Completion / Graduation'), ('SCHOLARSHIP', 'Scholarship Transfer'), ('ADMINISTRATIVE', 'Administrative Order'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Reason for Transfer')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='ldp_core.school', verbose_name='From School')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='ldp_core.person')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('to_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='ldp_core.school', verbose_name='To School')),
            ],
            options={
                'verbose_name': 'Transfer History',
                'verbose_name_plural': 'Transfer Histories',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
