# Generated by Django 4.2.30 on 2026-05-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0015_professionaljob'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('mimetype', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/mimetype/filename', verbose_name='Activity Banner'),
        ),
        migrations.AlterField(
            model_name='leadershipaward',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/mimetype/filename', verbose_name='Certificate / Photo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/mimetype/filename', verbose_name='Profile Banner'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/mimetype/filename'),
        ),
        migrations.AlterField(
            model_name='school',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/mimetype/filename', verbose_name='School Banner'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/mimetype/filename', verbose_name='School Logo'),
        ),
    ]
