# Generated by Django 4.2.30 on 2026-05-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0016_filedata_alter_activity_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/filename/mimetype', verbose_name='Activity Banner'),
        ),
        migrations.AlterField(
            model_name='leadershipaward',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/filename/mimetype', verbose_name='Certificate / Photo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/filename/mimetype', verbose_name='Profile Banner'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='school',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/filename/mimetype', verbose_name='School Banner'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ldp_core.filedata/content/filename/mimetype', verbose_name='School Logo'),
        ),
    ]
