# Generated by Django 4.2.30 on 2026-08-19 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0017_alter_activity_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('template_version', models.CharField(default='1.0', max_length=20)),
                ('mode', models.CharField(choices=[('UPSERT', 'Create and update')], default='UPSERT', max_length=20)),
                ('status', models.CharField(choices=[('VALIDATING', 'Validating'), ('READY', 'Ready to apply'), ('INVALID', 'Validation failed'), ('APPLYING', 'Applying'), ('APPLIED', 'Applied'), ('FAILED', 'Apply failed')], db_index=True, default='VALIDATING', max_length=20)),
                ('workbook_data', models.BinaryField()),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('create_count', models.PositiveIntegerField(default=0)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('failure_message', models.TextField(blank=True)),
                ('previewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=80)),
                ('row_number', models.PositiveIntegerField()),
                ('external_key', models.CharField(blank=True, max_length=500)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('UNCHANGED', 'Unchanged'), ('ERROR', 'Error')], max_length=20)),
                ('source_data', models.JSONField(default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_results', to='ldp_core.importjob')),
            ],
            options={
                'ordering': ['sheet_name', 'row_number'],
                'indexes': [models.Index(fields=['job', 'action'], name='import_job_action_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='importrowresult',
            constraint=models.UniqueConstraint(fields=('job', 'sheet_name', 'row_number'), name='unique_import_job_sheet_row'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', '-created_at'], name='import_status_created_idx'),
        ),
    ]
