# Generated by Django 4.2.30 on 2026-08-21 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldp_core', '0018_importjob_importrowresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_import', models.BooleanField(default=True, verbose_name='Allow data imports')),
                ('allow_export', models.BooleanField(default=True, verbose_name='Allow data exports')),
                ('school_sync_enabled', models.BooleanField(default=True, verbose_name='Schools')),
                ('user_sync_enabled', models.BooleanField(default=True, verbose_name='Users and profiles')),
                ('activity_sync_enabled', models.BooleanField(default=True, verbose_name='Activities')),
                ('award_sync_enabled', models.BooleanField(default=True, verbose_name='Leadership awards')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System settings',
                'verbose_name_plural': 'System settings',
            },
        ),
    ]
